esphome:
  name: "outdoor-brightness-meter"
  friendly_name: Outdoor brightness meter

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_api_encryption_key

ota:
  - platform: esphome
    password: !secret esp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Light-Meter-2 Fallback Hotspot"
    password: !secret esp_ap_password

captive_portal:

# Set up the pins of the microcontroller
i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

apds9960:
  address: 0x39
  update_interval: 60s

# Set up the sensor data measurements
sensor:
  - platform: apds9960
    type: CLEAR
    id: clear_light
    name: "Light intensity"
  - platform: apds9960
    type: RED
    id: red_light
    name: "Red light"
  - platform: apds9960
    type: GREEN
    id: green_light
    name: "Green light"
  - platform: apds9960
    type: BLUE
    id: blue_light
    name: "Blue light"


